/**
 * Generated from http://localhost:5178/openapi/v1.json.
 * Do not edit this file directly; run npm run generate:api.
 */

export interface AuthResponseDto {
  tokenType: string
  accessToken: string
  accessTokenExpiresAt: string
  refreshTokenExpiresAt: string
  user: UserResponseDto
}

export interface CreateUserRequestDto {
  email: string
  password: string
  displayName: string
  role?: string
}

export interface LoginRequestDto {
  email: string
  password: string
}

export interface ProblemDetails {
  type?: null | string
  title?: null | string
  status?: null | number | string
  detail?: null | string
  instance?: null | string
}

export interface RegisterRequestDto {
  email: string
  password: string
  displayName: string
}

export interface RoleResponseDto {
  name: string
  displayName: string
  description: string
  level: number | string
}

export interface UpdateRoleRequestDto {
  role: string
}

export interface UpdateUserRequestDto {
  email: string
  displayName: string
  role: string
}

export interface UserResponseDto {
  id: string
  email: string
  displayName: string
  createdAt: string
  role: string
}
